version: 2.0

jobs:
  "Flow one":
    docker:
      - image: circleci/ruby:2.2-node
    steps:
      - checkout
      - run: echo "Hello flow 1"

  "Flow two":
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run: echo "Hello flow 2"

  "Flow three":
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello flow 3"

workflows:
  version: 2
  build:
    jobs:
      - "Flow one"
      - "Flow two"
      - "Flow three"
